language: python
python:
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install coverage
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=codecov
after_success:
  - codecov
